### ISSUE TITLE
`dr` configuration file

### ISSUE THREAD

**Issue by yeuem1vannam** [yeuem1vannam/DivineRapier#1]
# Idea
From the format of `docker-compose.yml`, service names are defined by YAML
```yaml
# docker-compose.yml
version: '2'                                                                     
services:                                                                        
  web:
    # ...
  worker:
    # ...
```
So `dr` can read those names and interactive with them.

The configuration file should be `.divine-rapier.yaml`, and be placed at root folder of project
```
.
├── DivineRapier
├── .divine-rapier.yml
└── docker
```
```yaml
# .divine-rapier.yml
docker:
  context: ./docker
  docker-compose-file: ./docker/docker-compose.yml
services:
  web:
    context: ./web
  worker:
    context: ./worker
```
