### ISSUE TITLE
Draft idea

### ISSUE THREAD

**Issue by yeuem1vannam** [yeuem1vannam/DivineRapier#2]
Suppose I have an app that developing under microservices pattern and base on docker
```
.
├── web
├── api
├── worker
└── docker
    ├── Dockerfile.web
    ├── Dockerfile.worker
    ├── Dockerfile.api
    └── docker-compose.yml
```
```yaml
# docker-compose.yml
version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    links:
      - mysql-db
    volumes:
      - ../web:/workspace
    command: bundle exec rails s -b 0.0.0.0
  # api / worker
  mysql-db:
    image: mysql:5.7
```

I usually have to separate my terminals into several groups:
- PWD at `web` for working with code of web
- PWD at `api` for working with code of api
- PWD at `worker` for working with code of worker
- PWD at `docker` for executing commands such as: `docker-compose exec web rails c`

So I want to develop a gem that can solve that trouble by using a smart command that auto recognizing where I am, and which service I want to interactive with:
```bash
cd web

dr rails c
# cd ../docker && docker-compose exec web rails c

dr worker bundle exec sidekiq
# cd ../docker && docker-compose exec worker bundle exec sidekiq

dr bundle exec rspec
# cd ../docker && docker-compose exec web bundle exec rspec

dr api vim app/controller/api/v1/base.rb
# cd ../docker && docker-compose exec api /bin/sh -c 'cd /workspace && vim app/controller/api/v1/base.rb'
# OR
# cd ../api && vim app/controller/api/v1/base.rb
# OR
# vim ../api/app/controller/api/v1/base.rb

dr api!
# cd ../api

dr attach api
# docker attach docker_api_1

dr mysql-db mysql -u root -p
# cd ../docker && docker-compose exec mysql /bin/sh -c 'mysql -u root -p'
```

In the future, the gem can injected to application's executable files like gem `spring` did.
